


#include "WalkDefines.h"

DEFINE_LOG_CATEGORY(LogWalkPlayer)
DEFINE_LOG_CATEGORY(LogSplineMovement)
DEFINE_LOG_CATEGORY(LogSanity)
DEFINE_LOG_CATEGORY(LogInteraction)
DEFINE_LOG_CATEGORY(LogMonster)
DEFINE_LOG_CATEGORY(LogMonsterSound)
DEFINE_LOG_CATEGORY(LogGameplayVolume)
DEFINE_LOG_CATEGORY(LogBench)
DEFINE_LOG_CATEGORY(LogSitting)
DEFINE_LOG_CATEGORY(LogMusic)